### ISSUE TITLE
Work with Gorilla Mux?

### ISSUE THREAD

**Issue by MichaelHipp** [jordan-wright/unindexed#1]
Does anyone have some snippets to show how to make unindexed work with Gorilla Mux?

**Comment by jordan-wright** [comment]
Hi @MichaelHipp,

I've added an example showing how this can work with `mux` [here](https://github.com/jordan-wright/unindexed/blob/master/examples/mux/main.go).

Really, the easiest way to use the library is to take standard examples where `http.FileServer(http.Dir())` is used and replace `http.Dir` with `unindexed.Dir`.

I hope this helps!

**Comment by MichaelHipp** [comment]
I can't get that to work. When I send the browser to `localhost:8080` it says `localhost redirected you too many times`. It appears to be trying to re-write the url to `http://localhost:8080//`. This is when `../static` contains an empty `index.html` file. If `../static` is an empty dir, it says `404 page not found`. What am I missing?

**Comment by jordan-wright** [comment]
Oh how odd - I’m able to reproduce that on my end, too. Definitely not the intended result.

Let me do some troubleshooting and I’ll get this fixed. Thanks for the heads up!

**Comment by jordan-wright** [comment]
Ok, I just pushed up a couple of changes that should fix the issue. If you could give it another shot, I'd appreciated it!

The expected result when requesting a directory without an index.html file is "403 Forbidden".

Let me know if that fixes the problem for you!

**Comment by MichaelHipp** [comment]
Yes. That does indeed seem to have fixed it. And it's now giving `403 forbidden` which is prolly more correct. Thank you so much.
